monolog:
    channels: ['import']
    handlers:

        # Specific channels
        import:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%-import.log'
            channels: [import]