version: '3.5'
services:
  mysql:
    env_file: ./.env
    image: mysql:5.7
    ports:
    - ${MYSQL_HOST_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - ${MYSQL_HOST_VOLUME_PATH}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql:db
    ports:
    - ${PHP_MY_ADMIN_PORT}:80
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  php:
    env_file: .env
    build:
      context: docker/images/php-fpm7.3
      args:
        UID: ${HOST_UID}
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${RELATIVE_APP_PATH}:/var/www/html
    ports:
      - ${APPLICATION_WEB_PORT}:8000